export const UPDATE_COMPLETED_TODOS = "UPDATE_COMPLETED_TODOS";
export const UPDATE_TODOS = "UPDATE_TODOS";
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIURE = "FETCH_DATA_FAIURE";